### ISSUE TITLE
Add line source code at each frame of stack?

### ISSUE THREAD

**Issue by mgutz** [go-stack/stack#1]
This library is great. Would be nice to see the actual line's source code at each frame with context lines. Here's an example of one I did on node.js to help my team troubleshoot faster

https://raw.githubusercontent.com/barc/express-error/master/img/stack.png

I sometimes see error line when an error  is wrapped.

**Comment by ChrisHines** [comment]
Thanks.

Do you have any suggestions for how to implement this idea? The source code is not usually available once a Go binary is running in production.

**Comment by mgutz** [comment]
I wouldn't use it in production only while developing. It would slow things down too much to be of any use in production.

**Comment by ChrisHines** [comment]
I can see how that might be useful, but it is out of scope for this package. Perhaps you could write a utility that uses the source file and line number information from stack to do what you want.

**Comment by mgutz** [comment]
no problem. you can see how useful the context is on error on this gifcast https://github.com/mgutz/logxi. saves alot of time.
