### ISSUE TITLE
Possible to get the package name at a given call depth?

### ISSUE THREAD

**Issue by chmorgan** [go-stack/stack#16]
Any interest in having that feature in the package?

**Comment by chmorgan** [comment]
I'm asking because I'll put together a PR to add support for it if so.

**Comment by ChrisHines** [comment]
Yes, this could be useful. I think adding a new formatting verb that produces the package name is the way to go here. One of the forks has added `%k` for package name (https://github.com/getlantern/stack/commit/02f928aad224fbccd50d66edd776fc9d1e9f2f2b). We should also consider `%p`.

**Comment by chmorgan** [comment]
@ChrisHines submitted a PR with this change after reviewing and testing it.

**Comment by ChrisHines** [comment]
Implemented by #18.

**Comment by ChrisHines** [comment]
@chmorgan Thanks for the feature suggestion and being patient during my code review. The new feature was just released in v1.6.0.  🎉

**Comment by chmorgan** [comment]
@ChrisHines its no trouble, thanks for fixing the code up and getting this through vs. having it sit here. I'm not good at golang yet, especially not with slices. Coming next is PR against go-kit for the package name and package filtering.
