### ISSUE TITLE
go modules not use

### ISSUE THREAD

**Issue by thinkeridea** [go-stack/stack#22]
The import package path is inconsistent with your go. mod path, which makes it impossible to import the package.

go: gopkg.in/stack.v1@v1.8.0: go.mod has non-....v1 module path "github.com/go-stack/stack" at revision v1.8.0

**Comment by ChrisHines** [comment]
`github.com/go-stack/stack` is the correct import path for this package and has been for several years.

**Comment by kishaningithub** [comment]
@thinkeridea I am using go 1.13 and the below import in my go.mod works perfectly fine

```
require (
   github.com/go-stack/stack v1.8.0
)
```

**Comment by ChrisHines** [comment]
@kishaningithub Thanks for confirming.

I also have had no issues. Normally I try to let issue authors close their own issues, but I think this has been open without response long enough to close it.
