### ISSUE TITLE
Link to "the docs"

### ISSUE THREAD

**Issue by tlelson** [go-stack/stack#23]
Where are _"the docs"_ mentioned in the last line of the README ?

> See the docs for all of the supported formatting options

**Comment by ChrisHines** [comment]
They are in the code comments, which are viewable in a nicer format either via `go doc` locally or online at the "godoc reference" link at the top of the README, which takes you to: https://godoc.org/github.com/go-stack/stack. An alternate online version is also available at the experimental pkg.go.dev site here: https://pkg.go.dev/github.com/go-stack/stack?tab=doc.
