### ISSUE TITLE
Include full Apache License text

### ISSUE THREAD

**Issue by athos-ribeiro** [go-stack/stack#7]
Hi,

Item 4a of the Apache License 2.0 requires that whoever redistributes the licensed work, does it with a copy of the licence text [1]. Would you be willing to add such text to the repository so whoever is distributing this package does not need to attach a copy of the license to it?

Thanks!

[1] https://www.apache.org/licenses/LICENSE-2.0

**Comment by ChrisHines** [comment]
Thanks for pointing this issue out.

I think I prefer to change the license to MIT anyway.

See https://github.com/go-stack/stack/pull/8.

**Comment by athos-ribeiro** [comment]
That works as well. Thank you :)
